from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = PROJECT_ROOT / "data"


# Bronze
BRONZE_DIR = DATA_DIR / "bronze"

BRONZE_FLIGHTS = BRONZE_DIR / "flights"

BRONZE_REFERENCE = BRONZE_DIR / "reference"
BRONZE_REFERENCE_AIRLINES = BRONZE_REFERENCE / "airlines"
BRONZE_REFERENCE_AIRPORTS = BRONZE_REFERENCE / "airports"
BRONZE_REFERENCE_AIRPORT_IDS = BRONZE_REFERENCE / "airport_ids"


# Silver
SILVER_DIR = DATA_DIR / "silver"

SILVER_FLIGHTS = SILVER_DIR / "flights"

SILVER_REFERENCE = SILVER_DIR / "reference"
SILVER_REFERENCE_AIRLINES = SILVER_REFERENCE / "airlines"
SILVER_REFERENCE_AIRPORTS = SILVER_REFERENCE / "airports"
SILVER_REFERENCE_AIRPORT_IDS = SILVER_REFERENCE / "airport_ids"

SILVER_REPORTS = SILVER_DIR / "reports"
SILVER_FLIGHT_REPORTS = SILVER_REPORTS / "flights"
SILVER_REFERENCE_REPORTS = SILVER_REPORTS / "reference"

# Gold
GOLD_DIR = DATA_DIR / "gold"

GOLD_AIRLINE_RELIABILITY = GOLD_DIR / "airline_reliability"
GOLD_AIRPORT_RELIABILITY = GOLD_DIR / "airport_reliability"
GOLD_ROUTE_RELIABILITY = GOLD_DIR / "route_reliability"

